services:
  invocepdf:
    build: .
    container_name: invocepdf
    restart: unless-stopped

    ports:
      - "8080:8080"

    volumes:
      - ./data:/app/data

    environment:
      ASPNETCORE_URLS: "http://+:8080"